# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup MSBuild For Later Usage
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: '16.6.2'
    # Fetch NuGet Packages
    - name: NuGet Package Installer
      run: nuget restore
    # Run MSBuild
    - name: Build Solution
      run: msbuild "D:\a\NSMB-Editor\NSMB-Editor\NSMBe5.sln" /verbosity:minimal /property:Configuration=Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: NSMBe-win32
        path: D:\a\NSMB-Editor\NSMB-Editor\NSMBe5\bin\Release\
